module.exports = [
	{
		propName: 'Mediterranean Avenue',
		isPurchased: false,
		value: 60,
		color: 'section_Brown',
	},
	{
		propName: 'Baltic Avenue',
		isPurchased: false,
		value: 60,
		color: 'section_Brown',
	},
	{
		propName: 'Oriental Avenue',
		isPurchased: false,
		value: 100,
		color: 'section_Light-Blue',
	},
	{
		propName: 'Vermont Avenue',
		isPurchased: false,
		value: 100,
		color: 'section_Light-Blue',
	},
	{
		propName: 'Connecticut Avenue',
		isPurchased: false,
		value: 120,
		color: 'section_Light-Blue',
	},
	{
		propName: 'St. Charles Place',
		isPurchased: false,
		value: 140,
		color: 'section_Pink',
	},
	{
		propName: 'States Avenue',
		isPurchased: false,
		value: 140,
		color: 'section_Pink',
	},
	{
		propName: 'Virginia Avenue',
		isPurchased: false,
		value: 160,
		color: 'section_Pink',
	},
	{
		propName: 'St. James Place',
		isPurchased: false,
		value: 180,
		color: 'section_Orange',
	},
	{
		propName: 'Tennessee Avenue',
		isPurchased: false,
		value: 180,
		color: 'section_Orange',
	},
	{
		propName: 'New York Avenue',
		isPurchased: false,
		value: 200,
		color: 'section_Orange',
	},
	{
		propName: 'Kentucky Avenue',
		isPurchased: false,
		value: 220,
		color: 'section_Red',
	},
	{
		propName: 'Indiana Avenue',
		isPurchased: false,
		value: 220,
		color: 'section_Red',
	},
	{
		propName: 'Illinois Avenue',
		isPurchased: false,
		value: 240,
		color: 'section_Red',
	},
	{
		propName: 'Atlantic Avenue',
		isPurchased: false,
		value: 260,
		color: 'section_Yellow',
	},
	{
		propName: 'Ventnor Avenue',
		isPurchased: false,
		value: 260,
		color: 'section_Yellow',
	},
	{
		propName: 'Marvin Gardens',
		isPurchased: false,
		value: 280,
		color: 'section_Yellow',
	},
	{
		propName: 'Pacific Avenue',
		isPurchased: false,
		value: 300,
		color: 'section_Green',
	},
	{
		propName: 'North Carolina Avenue',
		isPurchased: false,
		value: 300,
		color: 'section_Green',
	},
	{
		propName: 'Pennsylvania Avenue',
		isPurchased: false,
		value: 320,
		color: 'section_Green',
	},
	{
		propName: 'Park Place',
		isPurchased: false,
		value: 350,
		color: 'section_Blue',
	},
	{
		propName: 'Boardwalk',
		isPurchased: false,
		value: 400,
		color: 'section_Blue',
	},
	{
		propName: 'Reading Railroad',
		isPurchased: false,
		value: 200,
		color: 'section_RR',
	},
	{
		propName: 'Pennsylvania Railroad',
		isPurchased: false,
		value: 200,
		color: 'section_RR',
	},
	{
		propName: 'B. & O. Railroad',
		isPurchased: false,
		value: 200,
		color: 'section_RR',
	},
	{
		propName: 'Short Line',
		isPurchased: false,
		value: 200,
		color: 'section_RR',
	},
	{
		propName: 'Electric Company',
		isPurchased: false,
		value: 150,
		color: 'section_Utility',
	},
	{
		propName: 'Water Works',
		isPurchased: false,
		value: 150,
		color: 'section_Utility',
	},
];